### ISSUE TITLE
Dockerfile exposes no ports but should

### ISSUE THREAD

**Issue by Wicaeed** [danny-avila/rag_api#126]
Something I noticed on the first setup of LibreChat on my Mac after being unable to use the RAG API features after following the install steps.

The Rag API service definition that the Librechat repo's docker-compose uses  has no **Docker Compose** port mappings. What is in use are environment arguments:
```
  rag_api:
    container_name: rag_api
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    restart: always
    depends_on:
      - vectordb
    env_file:
      - .env
```

In this repo, the rag_api Dockerfile also exposes no ports, but it really doesn't matter because in the docker-compose file ya'll have, you just map the host port 8000 to the container port 8000, negating the need to expose anything in the container.

Unfortunately the Docker Network for Librechat doesn't know that, and relies on the Dockerfile to expose a listening port in order for things to just seamlessly work over there.

It's an easy fix though, just add a line to the Dockerfile right before the last CMD line: 

```EXPOSE 8000```
